import type { Metadata } from "next";
import { ThemeProvider } from "@/components/layout/theme-provider";
import { ActiveThemeProvider } from "@/components/layout/active-theme";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { cookies } from "next/headers";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});
// const META_THEME_COLORS = {
//   light: "#ffffff",
//   dark: "#09090b",
// }

export const metadata: Metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies()
  const activeThemeValue = cookieStore.get("active_theme")?.value
  const isScaled = activeThemeValue?.endsWith("-scaled")

  return (
    <html lang="en" className={inter.variable} suppressHydrationWarning>
      <body
        className={cn(
          "bg-background overscroll-none font-sans antialiased",
          activeThemeValue ? `theme-${activeThemeValue}` : "",
          isScaled ? "theme-scaled" : "",
          
        )}
      >
        <ThemeProvider
        attribute='class'
        defaultTheme='system'
        enableSystem
        disableTransitionOnChange
        enableColorScheme>
          <ActiveThemeProvider>
        {children}
          </ActiveThemeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
